# Generated by Django 5.1.6 on 2025-02-25 17:52

from django.db import migrations
import uuid

def add_facilities(apps, schema_editor):
    """
    Adds several predefined facilities to the database.
    """
    Facility   = apps.get_model('resmio_app', 'Facility')
    facilities = [] 
    
    facilities_data = [
        {"name": "Main Conference Hall", "location": "Building A, Floor 1", "capacity": 200},
        {"name": "Training Room", "location": "Building B, Floor 2", "capacity": 4},
        {"name": "Outdoor Event Space", "location": "Campus Garden", "capacity": 500},
        {"name": "VIP Lounge", "location": "Building C, Floor 3", "capacity": 20},
        {"name": "Sports Complex", "location": "North Wing", "capacity": 1000},
    ]
    
    for facility in facilities_data:
        facilities.append(Facility(
            name=facility["name"],
            location=facility["location"],
            capacity=facility["capacity"]
        ))
    Facility.objects.bulk_create(facilities)

class Migration(migrations.Migration):

    dependencies = [
        ('resmio_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_facilities),
    ]
