# Generated by Django 5.1.6 on 2025-02-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resmio_app', '0002_auto_20250225_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='facility',
            name='location',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date'], name='resmio_app__date_4a8613_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='resmio_app__status_eace38_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['facility', 'date'], name='resmio_app__facilit_435a86_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['name'], name='resmio_app__name_f3fe04_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['location'], name='resmio_app__locatio_85039d_idx'),
        ),
    ]
